version: '3'
services:
  java-sdk:
    build:
      context: ./projects/java-sdk
    ports:
      - "8080:8080"
  dotnet-sdk:
    build:
      context: ./projects/dotnet-sdk
    ports:
      - "5243:5243"
  go-sdk:
    build:
      context: ./projects/go-sdk
    ports:
      - "8081:8081"
  node-sdk:
    build:
      context: ./projects/node-sdk
    ports:
      - "3002:3002"
