ARG SDK_BRANCH=main

FROM node:22 AS sdk-builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ARG SDK_BRANCH

WORKDIR /sdk
RUN git clone --branch ${SDK_BRANCH} --depth 1 https://github.com/fingerprintjs/node-sdk.git .
RUN npm install -g pnpm
RUN pnpm install && pnpm run build && pnpm pack


FROM node:22

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY . /app
WORKDIR /app

RUN npm install -g pnpm

COPY package.json tsconfig.json ./
COPY ./src ./src

COPY --from=sdk-builder /sdk/*.tgz /tmp/

RUN pnpm install && \
    SDK_TGZ=$(ls /tmp/*.tgz) && \
    pnpm add ${SDK_TGZ}

EXPOSE 3002

CMD ["pnpm", "start"]
